#!/bin/bash

echo "=== Configurable Composite Lines Feature Test ==="
echo ""
echo "🎉 PHANTOM LINE BUG SOLVED + CONFIGURABLE COMBO PLAY!"
echo ""
echo "WHAT'S NEW:"
echo "✅ Phantom line bug completely fixed"
echo "✅ Composite lines (combo play) now configurable"
echo "✅ Traditional Five-or-More rules by default"
echo "✅ Optional advanced combo gameplay available"
echo ""
echo "CONFIGURATION OPTIONS:"
echo ""
echo "1. TRADITIONAL MODE (default):"
echo "   - Only continuous 5+ piece lines are removed"
echo "   - Pattern XXX-Y-XXX is ignored (correct behavior)"
echo "   - Classic Five-or-More rules"
echo ""
echo "2. COMBO MODE (optional):"
echo "   - Gap-separated patterns like 2+3, 3+2, 2+2+1 are detected"
echo "   - Pattern XXX-Y-XXX becomes '2+3 combo' worth bonus points"
echo "   - Advanced gameplay with achievements"
echo ""
echo "HOW TO ENABLE COMBO MODE:"
echo "1. Create config file: ~/.config/five-or-more/game-constants.conf"
echo "2. Add this section:"
echo "   [GameRules]"
echo "   ENABLE_COMPOSITE_LINES=true"
echo "3. Restart the game"
echo ""
echo "TESTING BOTH MODES:"
echo ""
echo "DEFAULT (Traditional Mode):"
echo "- Pattern XXX-Y-XXX should NOT be removed"
echo "- Only continuous XXXXX should be removed"
echo ""
echo "With ENABLE_COMPOSITE_LINES=true (Combo Mode):"
echo "- Pattern XXX-Y-XXX should be detected as '2+3 combo'"
echo "- Achievement notification should appear"
echo "- Bonus points awarded for combo patterns"
echo ""
echo "Press Enter to start the game in traditional mode..."
read -r

# Start the game
echo "Starting Five or More in traditional mode (composite lines disabled)..."
./builddir/src/five-or-more