/*
 * Five or More - Fallback Resource Generator
 * Copyright © 2024 Five or More Contributors
 *
 * This game is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see <https://www.gnu.org/licenses/>.
 */

/**
 * Fallback resource generator for creating emergency resources when all else fails
 */
public class FallbackGenerator : Object {
    private static FallbackGenerator? instance = null;
    
    // Default color schemes for fallback themes
    private const string[] DEFAULT_PIECE_COLORS = {
        "#FFFF00", "#FF00FF", "#00FF00", "#FF0000", 
        "#0000FF", "#00FFFF", "#FF8000"
    };
    
    private const string DEFAULT_BORDER_COLOR = "#000000";
    private const int DEFAULT_BORDER_WIDTH = 2;
    
    construct {
    }
    
    public static FallbackGenerator get_instance() {
        if (instance == null) {
            instance = new FallbackGenerator();
        }
        return instance;
    }
    
    /**
     * Generate a minimal fallback SVG theme
     */
    public string generate_fallback_svg_theme(string? theme_name = null) {
        var name = theme_name ?? "fallback";
        
        var builder = new StringBuilder();
        builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        builder.append("<!-- Fallback SVG theme generated by Five or More -->\n");
        builder.append("<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"400\" height=\"700\" version=\"1.1\">\n");
        
        // Add metadata
        builder.append("  <metadata>\n");
        builder.append("    <title>%s Fallback Theme</title>\n".printf(name.up()));
        builder.append("    <description>Emergency fallback theme for Five or More</description>\n");
        builder.append("    <generator>Five or More Fallback Generator</generator>\n");
        builder.append("  </metadata>\n\n");
        
        // Add CSS styles
        builder.append("  <defs>\n");
        builder.append("    <style>\n");
        builder.append("      :root {\n");
        
        for (int i = 0; i < DEFAULT_PIECE_COLORS.length; i++) {
            builder.append("        --piece-color-%d: %s;\n".printf(i, DEFAULT_PIECE_COLORS[i]));
        }
        
        builder.append("        --border-color: %s;\n".printf(DEFAULT_BORDER_COLOR));
        builder.append("        --border-width: %d;\n".printf(DEFAULT_BORDER_WIDTH));
        builder.append("      }\n\n");
        
        builder.append("      .piece {\n");
        builder.append("        stroke: var(--border-color);\n");
        builder.append("        stroke-width: var(--border-width);\n");
        builder.append("        opacity: 1.0;\n");
        builder.append("      }\n\n");
        
        for (int i = 0; i < DEFAULT_PIECE_COLORS.length; i++) {
            builder.append("      .piece-%d { fill: var(--piece-color-%d); }\n".printf(i, i));
        }
        
        builder.append("\n      /* Animation states */\n");
        builder.append("      .normal { opacity: 1.0; }\n");
        builder.append("      .shrinking { opacity: 0.8; }\n");
        builder.append("      .growing { opacity: 1.0; }\n");
        builder.append("      .pulsing { opacity: 0.9; }\n");
        builder.append("    </style>\n");
        
        // Add simple shadow filter
        builder.append("    <filter id=\"shadow\" x=\"-50%\" y=\"-50%\" width=\"200%\" height=\"200%\">\n");
        builder.append("      <feDropShadow dx=\"1\" dy=\"1\" stdDeviation=\"1\" flood-opacity=\"0.2\"/>\n");
        builder.append("    </filter>\n");
        builder.append("  </defs>\n\n");
        
        // Generate sprite grid
        builder.append("  <g id=\"theme-sprites\">\n");
        
        for (int type = 0; type < DEFAULT_PIECE_COLORS.length; type++) {
            var y = 50 + (type * 100);
            
            // Normal animation (column 0)
            builder.append("    <circle class=\"piece piece-%d normal\" cx=\"50\" cy=\"%d\" r=\"37.5\" filter=\"url(#shadow)\"/>\n".printf(type, y));
            
            // Shrinking animation (column 1)
            builder.append("    <circle class=\"piece piece-%d shrinking\" cx=\"150\" cy=\"%d\" r=\"33.75\" filter=\"url(#shadow)\"/>\n".printf(type, y));
            
            // Growing animation (column 2)
            builder.append("    <circle class=\"piece piece-%d growing\" cx=\"250\" cy=\"%d\" r=\"41.25\" filter=\"url(#shadow)\"/>\n".printf(type, y));
            
            // Pulsing animation (column 3)
            builder.append("    <circle class=\"piece piece-%d pulsing\" cx=\"350\" cy=\"%d\" r=\"37.5\" filter=\"url(#shadow)\"/>\n".printf(type, y));
        }
        
        builder.append("  </g>\n");
        builder.append("</svg>\n");
        
        return builder.str;
    }
    
    /**
     * Generate a fallback color scheme
     */
    public ColorScheme generate_fallback_color_scheme(string? scheme_name = null) {
        var name = scheme_name ?? "Fallback";
        
        var scheme = new ColorScheme();
        scheme.name = name;
        scheme.piece_colors = DEFAULT_PIECE_COLORS;
        scheme.border_color = DEFAULT_BORDER_COLOR;
        scheme.border_width = DEFAULT_BORDER_WIDTH;
        scheme.opacity = 1.0;
        scheme.high_contrast = false;
        
        return scheme;
    }
    
    /**
     * Generate high contrast fallback theme
     */
    public string generate_high_contrast_fallback_theme() {
        var high_contrast_colors = new string[] {
            "#FFFFFF", "#000000", "#FFFF00", "#FF0000",
            "#0000FF", "#00FF00", "#FF00FF"
        };
        
        var builder = new StringBuilder();
        builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        builder.append("<!-- High contrast fallback theme -->\n");
        builder.append("<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"400\" height=\"700\" version=\"1.1\">\n");
        
        builder.append("  <defs>\n");
        builder.append("    <style>\n");
        builder.append("      :root {\n");
        
        for (int i = 0; i < high_contrast_colors.length; i++) {
            builder.append("        --piece-color-%d: %s;\n".printf(i, high_contrast_colors[i]));
        }
        
        builder.append("        --border-color: #000000;\n");
        builder.append("        --border-width: 4;\n"); // Thicker borders for high contrast
        builder.append("      }\n\n");
        
        builder.append("      .piece {\n");
        builder.append("        stroke: var(--border-color);\n");
        builder.append("        stroke-width: var(--border-width);\n");
        builder.append("        opacity: 1.0;\n");
        builder.append("      }\n\n");
        
        for (int i = 0; i < high_contrast_colors.length; i++) {
            builder.append("      .piece-%d { fill: var(--piece-color-%d); }\n".printf(i, i));
        }
        
        builder.append("    </style>\n");
        builder.append("  </defs>\n\n");
        
        // Generate high contrast sprites with thicker borders
        builder.append("  <g id=\"theme-sprites\">\n");
        
        for (int type = 0; type < high_contrast_colors.length; type++) {
            var y = 50 + (type * 100);
            
            for (int anim = 0; anim < 4; anim++) {
                var x = 50 + (anim * 100);
                var radius = 37.5;
                
                if (anim == 1) radius = 33.75; // shrinking
                else if (anim == 2) radius = 41.25; // growing
                
                builder.append("    <circle class=\"piece piece-%d\" cx=\"%d\" cy=\"%d\" r=\"%.2f\"/>\n".printf(type, x, y, radius));
            }
        }
        
        builder.append("  </g>\n");
        builder.append("</svg>\n");
        
        return builder.str;
    }
    
    /**
     * Generate colorblind-friendly fallback theme
     */
    public string generate_colorblind_fallback_theme(AccessibilityProfileType profile) {
        string[] colorblind_colors;
        
        switch (profile) {
            case AccessibilityProfileType.COLORBLIND_DEUTERANOPIA:
                // Red-green colorblind friendly
                colorblind_colors = {
                    "#0173B2", "#DE8F05", "#CC78BC", "#029E73",
                    "#FBAFE4", "#949494", "#ECE133"
                };
                break;
                
            case AccessibilityProfileType.COLORBLIND_PROTANOPIA:
                // Red-green colorblind friendly (different variant)
                colorblind_colors = {
                    "#1f77b4", "#ff7f0e", "#2ca02c", "#d62728",
                    "#9467bd", "#8c564b", "#e377c2"
                };
                break;
                
            case AccessibilityProfileType.COLORBLIND_TRITANOPIA:
                // Blue-yellow colorblind friendly
                colorblind_colors = {
                    "#FF6B6B", "#4ECDC4", "#45B7D1", "#96CEB4",
                    "#FFEAA7", "#DDA0DD", "#98D8C8"
                };
                break;
                
            default:
                colorblind_colors = DEFAULT_PIECE_COLORS;
                break;
        }
        
        var builder = new StringBuilder();
        builder.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        builder.append("<!-- Colorblind-friendly fallback theme -->\n");
        builder.append("<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"400\" height=\"700\" version=\"1.1\">\n");
        
        builder.append("  <defs>\n");
        builder.append("    <style>\n");
        builder.append("      :root {\n");
        
        for (int i = 0; i < colorblind_colors.length; i++) {
            builder.append("        --piece-color-%d: %s;\n".printf(i, colorblind_colors[i]));
        }
        
        builder.append("        --border-color: #000000;\n");
        builder.append("        --border-width: 3;\n");
        builder.append("      }\n\n");
        
        builder.append("      .piece {\n");
        builder.append("        stroke: var(--border-color);\n");
        builder.append("        stroke-width: var(--border-width);\n");
        builder.append("        opacity: 1.0;\n");
        builder.append("      }\n\n");
        
        for (int i = 0; i < colorblind_colors.length; i++) {
            builder.append("      .piece-%d { fill: var(--piece-color-%d); }\n".printf(i, i));
        }
        
        // Add patterns for additional differentiation
        builder.append("\n      /* Additional patterns for colorblind accessibility */\n");
        builder.append("      .piece-0 { fill-opacity: 1.0; }\n");
        builder.append("      .piece-1 { fill-opacity: 0.9; }\n");
        builder.append("      .piece-2 { fill-opacity: 0.8; }\n");
        builder.append("      .piece-3 { fill-opacity: 0.7; }\n");
        builder.append("      .piece-4 { fill-opacity: 0.9; }\n");
        builder.append("      .piece-5 { fill-opacity: 0.8; }\n");
        builder.append("      .piece-6 { fill-opacity: 0.7; }\n");
        
        builder.append("    </style>\n");
        
        // Add pattern definitions for texture differentiation
        builder.append("    <defs>\n");
        builder.append("      <pattern id=\"dots\" patternUnits=\"userSpaceOnUse\" width=\"10\" height=\"10\">\n");
        builder.append("        <circle cx=\"5\" cy=\"5\" r=\"2\" fill=\"white\" opacity=\"0.3\"/>\n");
        builder.append("      </pattern>\n");
        builder.append("      <pattern id=\"stripes\" patternUnits=\"userSpaceOnUse\" width=\"8\" height=\"8\">\n");
        builder.append("        <rect width=\"4\" height=\"8\" fill=\"white\" opacity=\"0.2\"/>\n");
        builder.append("      </pattern>\n");
        builder.append("    </defs>\n");
        
        builder.append("  </defs>\n\n");
        
        // Generate sprites with patterns
        builder.append("  <g id=\"theme-sprites\">\n");
        
        for (int type = 0; type < colorblind_colors.length; type++) {
            var y = 50 + (type * 100);
            
            for (int anim = 0; anim < 4; anim++) {
                var x = 50 + (anim * 100);
                var radius = 37.5;
                
                if (anim == 1) radius = 33.75; // shrinking
                else if (anim == 2) radius = 41.25; // growing
                
                builder.append("    <circle class=\"piece piece-%d\" cx=\"%d\" cy=\"%d\" r=\"%.2f\"/>\n".printf(type, x, y, radius));
                
                // Add pattern overlay for some pieces
                if (type % 2 == 0) {
                    builder.append("    <circle cx=\"%d\" cy=\"%d\" r=\"%.2f\" fill=\"url(#dots)\"/>\n".printf(x, y, radius));
                } else if (type % 3 == 0) {
                    builder.append("    <circle cx=\"%d\" cy=\"%d\" r=\"%.2f\" fill=\"url(#stripes)\"/>\n".printf(x, y, radius));
                }
            }
        }
        
        builder.append("  </g>\n");
        builder.append("</svg>\n");
        
        return builder.str;
    }
    
    /**
     * Save fallback resource to file
     */
    public void save_fallback_resource(string content, string file_path) throws Error {
        var file = File.new_for_path(file_path);
        var parent_dir = file.get_parent();
        
        if (parent_dir != null && !parent_dir.query_exists()) {
            parent_dir.make_directory_with_parents();
        }
        
        file.replace_contents(content.data, null, false, FileCreateFlags.REPLACE_DESTINATION, null);
        debug("Saved fallback resource: %s (%d bytes)", file_path, content.length);
    }
    
    /**
     * Generate all fallback resources
     */
    public void generate_all_fallback_resources(string output_dir) throws Error {
        var dir = File.new_for_path(output_dir);
        if (!dir.query_exists()) {
            dir.make_directory_with_parents();
        }
        
        // Generate standard fallback theme
        var standard_theme = generate_fallback_svg_theme("standard");
        save_fallback_resource(standard_theme, Path.build_filename(output_dir, "fallback-standard.svg"));
        
        // Generate high contrast theme
        var high_contrast_theme = generate_high_contrast_fallback_theme();
        save_fallback_resource(high_contrast_theme, Path.build_filename(output_dir, "fallback-high-contrast.svg"));
        
        // Generate colorblind-friendly themes
        var deuteranopia_theme = generate_colorblind_fallback_theme(AccessibilityProfileType.COLORBLIND_DEUTERANOPIA);
        save_fallback_resource(deuteranopia_theme, Path.build_filename(output_dir, "fallback-deuteranopia.svg"));
        
        var protanopia_theme = generate_colorblind_fallback_theme(AccessibilityProfileType.COLORBLIND_PROTANOPIA);
        save_fallback_resource(protanopia_theme, Path.build_filename(output_dir, "fallback-protanopia.svg"));
        
        var tritanopia_theme = generate_colorblind_fallback_theme(AccessibilityProfileType.COLORBLIND_TRITANOPIA);
        save_fallback_resource(tritanopia_theme, Path.build_filename(output_dir, "fallback-tritanopia.svg"));
        
        debug("Generated all fallback resources in: %s", output_dir);
    }
}